language: python
sudo: required
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - sudo apt-get install python-matplotlib
  - sudo apt-get install python-psutil
  - export MPLBACKEND="agg"
script:
  - tests/PID.py
  - tests/feedForward.py